{% set name = "dialite" %}
{% set version = "0.6.0" %}
{% set sha256 = "8d36c144f5c2388431b9e00a5eae817648df9277e22b5cac29c678663c7cf52f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - dialite

about:
  home: http://dialite.readthedocs.io
  doc_url: http://dialite.readthedocs.io
  dev_url: https://github.com/flexxui/dialite
  summary: small library to show simple dialogs to the user, without the need for a heavy GUI toolkit.
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
