{% set name = "dialite" %}
{% set version = "0.5.2" %}
{% set sha256 = "108c27255100a726a22fcce87cd3eafa33926a54e5f74770179c31ddb3525105" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - dialite

about:
  home: http://dialite.readthedocs.io
  doc_url: http://dialite.readthedocs.io
  dev_url: https://github.com/flexxui/dialite
  summary: small library to show simple dialogs to the user, without the need for a heavy GUI toolkit.
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
