travis:
  secure:
    BINSTAR_TOKEN: bPj5tdnCwPBKMuuwBgpRB9Yxq5yuQXxK7pZLf3phG2RgdPfJqLoU35sjXFt89P4LHL9f7qEXEEURfoyK25Is7pE4zFKHP5wRQvLhvloioeS+h5Enrt26XZfBscAw8F4QmpZv5WOdqmNYd6FqNgRLynreN5tJ4BfCaGUX7KvlR76gaMisGFIqVR3XXXXSJfTiLtgaReupM4x/ozs6CdWSeJIEQq7Z/VFPzLRWTezxu44RsEKit1lSapRHXGwpPYB25q5EVtFzy8iTc/P3s+Bx2mowrRCZQXmCrWDCMggiJNADdFU4u4JP1Fhcip23Iy9YNOvluuLiz0uQQorczLfK8wKiho/cjLrbwOnpo0eQaQgsu+IrFPik7GuLgNlYb/6uc/qjhrjMYpeqS9OU2QwIcyuO2c0sTE1IUKhtLyvvEz4a2XXxmeUrUKZP5CBoZeQxxi/2F7lMHlInXpcHIY1kUtNM25ML6n4tpHqMEgnDgrGxNjgMk//ql1Hqymd3uLraMIPPcB+4oCS6psNbx3zHZLrlDCbge5/hHyhp59aJE7QPyLrkJ294J6LqOlgrXWmoC62dcL8pQpjb5gO88KW9gRwl+vNoJtHGxZWoZRMT2iMnGJoqtQJ16LhrExxA5xHErvj6Q4Rh8lhRVcNE/Pkvt4lfQSPGzZ7rVtf7jNKKCe4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
