travis:
  secure:
    BINSTAR_TOKEN: jP3T4jgfI09hG92oI1ayQ8o+4lQaAppaAJ7S2lBYSUNGrJ8zp6AENEjw8bdZvVGLF3S91z0P9wZzAqY7ANAR2SIAni+KMrUVkSTHFJ5zHCaxm78f4Aeq7SJx2lLObRyr43j8tjgU0NY67kci7z+ix1UbFZpv6J08OEUOitJ1hozSFBt3eAk3igDkSYrBDJ2Kx7unpTcFMjfyPPijOIwTHUnc4LXJocSC9FGmfjachSRtkEiaIn23gVvGSpn5BbWSxP+adF6F/oqQ1SDfA/puQFrIF6M9g6nmUGvly6XhT/isFfKNvUUUCeOydCqKiBauBj7qxHvydWa5LfCABOGd2ocATzW7P9bvAkGVDO2fQBpvba0CNLIpjETVmLFBKsDpgyRZznW2iaBq0kVLzKYH8ah2UQ2tzPp++C+IrfIfvho3PfPVr83upoHStYcNdJgwCYYDg58k7yx+8GMyFJ+NpxxIwmwI1+yxGlFPpUZog7UlgGxGZWKWJsPSovIrBVgWAAIwA7ThHzrfCYXnENamA8tSmrbTkeyvSVZd7++cnqGPL1X8n6cDuiAL339+7ATElQCUdE2yYRtJo88Ecjl0QJR+roSRgzsE0tNXmy6/+4RjWJrocJRT7UCz7SOtHeUYOFlP/IOvgle2g2Q8ZMmQvaLESEHmw4WEQQQS8qF4Bi8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
